const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('nav');
if(toggle){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.textContent=open?'Close':'Menu'});}
/* Paste the Google Sheet ID between the quotes to activate automatic content updates. */
const sheetId="16pFkeFT9tocUKJKI_FNg8JPKKE7uD-yyqHNZv26aik4";
const csvUrl=tab=>`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}`;
function csvRows(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
async function readSheet(tab){const response=await fetch(csvUrl(tab));if(!response.ok)throw new Error(`Could not load ${tab}`);const rows=csvRows(await response.text());const headerIndex=rows.findIndex(row=>row.some(cell=>cell.trim()==='Display'));if(headerIndex<0)throw new Error(`The ${tab} tab is missing its Display header`);const [headers,...data]=rows.slice(headerIndex);return data.map(row=>Object.fromEntries(headers.map((h,i)=>[h.trim(),(row[i]||'').trim()])));}
const initials=name=>(name||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function personCard(p){const image=p['Image URL']?`<img src="${escapeHtml(p['Image URL'])}" alt="${escapeHtml(p.Name)}">`:initials(p.Name);return `<article class="person"><div class="avatar">${image}</div><h3>${escapeHtml(p.Name)}</h3><div class="role">${escapeHtml(p.Role)}</div><p>${escapeHtml(p.Bio||p['Research interests'])}</p></article>`;}
async function updatePeople(){const grids=document.querySelectorAll('.people-grid');if(!grids.length||!sheetId)return;const data=(await readSheet('People')).filter(p=>(p.Display||'').toLowerCase()==='yes').sort((a,b)=>(+a.Order||999)-(+b.Order||999));grids[0].innerHTML=data.filter(p=>(p.Status||'').toLowerCase()!=='alumni').map(personCard).join('');if(grids[1])grids[1].innerHTML=data.filter(p=>(p.Status||'').toLowerCase()==='alumni').map(personCard).join('');}
async function updatePublications(){const target=document.querySelector('.publication')?.parentElement;if(!target||!sheetId)return;const data=(await readSheet('Publications')).filter(p=>(p.Display||'').toLowerCase()==='yes'&&p.Title).sort((a,b)=>+b.Year-+a.Year||(+a.Order||999)-(+b.Order||999));if(!data.length)return;target.innerHTML=data.map(p=>`<div class="publication"><time>${escapeHtml(p.Year)}</time><div><h3>${escapeHtml(p.Title)}</h3><p>${escapeHtml(p.Authors)} · <em>${escapeHtml(p.Venue)}</em>${p['Volume / pages']?`, ${escapeHtml(p['Volume / pages'])}`:''}${p['Link URL']?` · <a href="${escapeHtml(p['Link URL'])}" target="_blank" rel="noopener">${escapeHtml(p['Link label']||'Link')}</a>`:''}</p></div></div>`).join('');}
Promise.all([updatePeople(),updatePublications()]).catch(error=>console.warn('Google Sheet content not loaded:',error));
function personCard(p){const image=p['Image URL']?`<img src="${escapeHtml(p['Image URL'])}" alt="${escapeHtml(p.Name)}">`:initials(p.Name);const links=[p.Email&&`<a href="mailto:${escapeHtml(p.Email)}">Email</a>`,p.ORCID&&`<a href="${escapeHtml(p.ORCID)}" target="_blank" rel="noopener">ORCID</a>`,p['Google Scholar']&&`<a href="${escapeHtml(p['Google Scholar'])}" target="_blank" rel="noopener">Scholar</a>`].filter(Boolean).join('');return `<article class="person"><div class="avatar">${image}</div><h3>${escapeHtml(p.Name)}</h3><div class="role">${escapeHtml(p.Role)}</div><p>${escapeHtml(p.Bio||p['Research interests'])}</p>${links?`<div class="person-links">${links}</div>`:''}</article>`;}
async function updateAnnouncements(){const target=document.querySelector('.news-grid');if(!target||!sheetId)return;const data=(await readSheet('Announcements')).filter(x=>(x.Display||'').toLowerCase()==='yes'&&x.Title).sort((a,b)=>new Date(b.Date)-new Date(a.Date)).slice(0,3);if(!data.length)return;target.innerHTML=data.map(x=>`<article><time>${escapeHtml(x.Date)}</time><h3>${escapeHtml(x.Title)}</h3><p>${escapeHtml(x.Summary)}</p>${x['Link URL']?`<a href="${escapeHtml(x['Link URL'])}">${escapeHtml(x['Link label']||'Read more')} →</a>`:''}</article>`).join('');}
async function updateResearch(){const target=document.querySelector('.research-list');if(!target||!sheetId)return;const data=(await readSheet('Research')).filter(x=>(x.Display||'').toLowerCase()==='yes').sort((a,b)=>(+a.Order||999)-(+b.Order||999));target.innerHTML=data.map((x,i)=>`<article class="research-item"><span>${String(i+1).padStart(2,'0')}</span><h2>${escapeHtml(x.Title)}</h2><p>${escapeHtml(x.Description)}</p>${x['Image URL']?`<img class="research-figure" src="${escapeHtml(x['Image URL'])}" alt="${escapeHtml(x['Image alt']||x.Title)}">`:''}</article>`).join('');}
Promise.all([updateAnnouncements(),updateResearch()]).catch(error=>console.warn('Google Sheet content not loaded:',error));
/* IIT Bombay identity and arXiv source are kept here so every page stays consistent. */
document.querySelectorAll('.brand span:last-child').forEach(x=>x.innerHTML='Quantum Information<br>Theory Group');
document.querySelectorAll('footer span:last-child').forEach(x=>x.textContent='Department of Physics · Indian Institute of Technology Bombay');
if(location.pathname.endsWith('index.html')||location.pathname==='/'){const e=document.querySelector('.hero .eyebrow');if(e)e.textContent='Department of Physics · Indian Institute of Technology Bombay';}
