const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('nav');
if(toggle){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.textContent=open?'Close':'Menu'});}
/* Paste the Google Sheet ID between the quotes to activate automatic content updates. */
const sheetId="16pFkeFT9tocUKJKI_FNg8JPKKE7uD-yyqHNZv26aik4";
const csvUrl=tab=>`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}`;
function csvRows(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
async function readSheet(tab){const response=await fetch(csvUrl(tab));if(!response.ok)throw new Error(`Could not load ${tab}`);const rows=csvRows(await response.text());const headerIndex=rows.findIndex(row=>row.some(cell=>cell.trim().endsWith('Display')));if(headerIndex<0)throw new Error(`The ${tab} tab is missing its Display header`);const [rawHeaders,...data]=rows.slice(headerIndex);const headers=rawHeaders.map((h,i)=>i===0?'Display':h.trim());return data.map(row=>Object.fromEntries(headers.map((h,i)=>[h,(row[i]||'').trim()])));}
const initials=name=>(name||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function imageUrl(url=''){const id=url.match(/drive\.google\.com\/(?:file\/d\/|open\?id=|uc\?id=)([-\w]+)/)?.[1]||url.match(/[?&]id=([-\w]+)/)?.[1];return id?`https://drive.google.com/thumbnail?id=${id}&sz=w1000`:url;}
async function updatePeople(){const grids=document.querySelectorAll('.people-grid');if(!grids.length||!sheetId)return;const data=(await readSheet('People')).filter(p=>(p.Display||'').toLowerCase()==='yes').sort((a,b)=>(+a.Order||999)-(+b.Order||999));grids[0].innerHTML=data.filter(p=>(p.Status||'').toLowerCase()!=='alumni').map(personCard).join('');if(grids[1])grids[1].innerHTML=data.filter(p=>(p.Status||'').toLowerCase()==='alumni').map(personCard).join('');}
async function updatePublications(){const target=document.querySelector('.publication')?.parentElement;if(!target||!sheetId)return;const data=(await readSheet('Publications')).filter(p=>(p.Display||'').toLowerCase()==='yes'&&p.Title).sort((a,b)=>+b.Year-+a.Year||(+a.Order||999)-(+b.Order||999));if(!data.length)return;target.innerHTML=data.map(p=>{const source=p.Venue||p['Volume / pages']||p['arXiv ID']||'arXiv';const date=[p.Month,p.Year].filter(Boolean).join(' ');return `<div class="publication"><time>${escapeHtml(date)}</time><div><h3>${escapeHtml(p.Title)}</h3><p>${escapeHtml(p.Authors)} · <em>${escapeHtml(source)}</em>${p['Link URL']?` · <a href="${escapeHtml(p['Link URL'])}" target="_blank" rel="noopener">${escapeHtml(p['Link label']||'arXiv')}</a>`:''}</p></div></div>`;}).join('');}
Promise.all([updatePeople(),updatePublications()]).catch(error=>console.warn('Google Sheet content not loaded:',error));
const icon={email:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 5.5h17v13h-17zM4 6l8 6 8-6"/></svg>',scholar:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 9.5 12 4l10 5.5L12 15zM6 12.2V16c3.5 2.1 8.5 2.1 12 0v-3.8M20 10v6"/></svg>',orcid:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M8.3 8.5v7M8.3 6.5v.1M11 8.5h2.2a3.5 3.5 0 0 1 0 7H11z"/></svg>',home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 11 9-7 9 7v9H3zM9 20v-5h6v5"/></svg>'};
function personCard(p){const photo=imageUrl(p['Image URL']);const image=photo?`<img src="${escapeHtml(photo)}" alt="${escapeHtml(p.Name)}" style="object-fit:contain;background:#e8ebe1" onerror="this.parentElement.textContent='${initials(p.Name)}'">`:initials(p.Name);const link=(url,type,label,mail=false)=>url?`<a class="person-icon" href="${mail?'mailto:':''}${escapeHtml(url)}" ${mail?'': 'target="_blank" rel="noopener"'} aria-label="${label}" title="${label}">${icon[type]}</a>`:'';const links=[link(p.Email,'email',`Email ${p.Name}`,true),link(p['Google Scholar'],'scholar',`${p.Name} on Google Scholar`),link(p.ORCID,'orcid',`${p.Name} on ORCID`),link(p['Personal Homepage'],'home',`${p.Name}'s personal homepage`)].filter(Boolean).join('');const interests=p['Research interests']?`<p class="interests">${escapeHtml(p['Research interests'])}</p>`:'';const bio=p.Bio?`<details class="person-bio"><summary>About</summary><p>${escapeHtml(p.Bio)}</p></details>`:'';return `<article class="person"><div class="avatar">${image}</div><h3>${escapeHtml(p.Name)}</h3><div class="role">${escapeHtml(p.Role)}</div>${interests}${bio}${links?`<div class="person-links">${links}</div>`:''}</article>`;}
async function updateAnnouncements(){const target=document.querySelector('.news-grid');if(!target||!sheetId)return;const data=(await readSheet('Announcements')).filter(x=>(x.Display||'').toLowerCase()==='yes'&&x.Title).sort((a,b)=>new Date(b.Date)-new Date(a.Date)).slice(0,3);if(!data.length)return;target.innerHTML=data.map(x=>`<article><time>${escapeHtml(x.Date)}</time><h3>${escapeHtml(x.Title)}</h3><p>${escapeHtml(x.Summary)}</p>${x['Link URL']?`<a href="${escapeHtml(x['Link URL'])}">${escapeHtml(x['Link label']||'Read more')} →</a>`:''}</article>`).join('');}
async function updateResearch(){const target=document.querySelector('.research-list');if(!target||!sheetId)return;const data=(await readSheet('Research')).filter(x=>(x.Display||'').toLowerCase()==='yes').sort((a,b)=>(+a.Order||999)-(+b.Order||999));target.innerHTML=data.map((x,i)=>{const photo=imageUrl(x['Image URL']);return `<article class="research-item"><span>${String(i+1).padStart(2,'0')}</span><h2>${escapeHtml(x.Title)}</h2><p>${escapeHtml(x.Description)}</p>${photo?`<img class="research-figure" src="${escapeHtml(photo)}" alt="${escapeHtml(x['Image alt']||x.Title)}">`:''}</article>`;}).join('');}
Promise.all([updateAnnouncements(),updateResearch()]).catch(error=>console.warn('Google Sheet content not loaded:',error));
/* IIT Bombay identity and arXiv source are kept here so every page stays consistent. */
document.querySelectorAll('.brand span:last-child').forEach(x=>x.innerHTML='Quantum Information<br>Theory Group');
document.querySelectorAll('footer span:last-child').forEach(x=>x.textContent='Department of Physics · Indian Institute of Technology Bombay');
if(location.pathname.endsWith('index.html')||location.pathname==='/'){const e=document.querySelector('.hero .eyebrow');if(e)e.textContent='Department of Physics · Indian Institute of Technology Bombay';}
